config/routes.rb
BasicAuth::Application.routes.draw do
  root :to=>"home#index"
  get "signed_out" => "authentication#signed_out"
  get "forgot_password" => "authentication#forgot_password"
  get "password_sent" => "authentication#password_sent"

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"

  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"

  get "account_settings" => "authentication#account_settings"
  put "account_settings" => "authentication#set_account_info"

  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"
  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"

  get "admin_users" => "admin#users"
  delete "user/:id" => "admin#delete_user", :as => "user"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicAuth</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p>
<% if current_user %>
    Logged in as <%= current_user.username %>.
    <%= link_to "Sign Out", signed_out_path %>
    <%= link_to "Account Settings", account_settings_path %>
      <% if current_user.is_admin %>
          <%= link_to "Admin", admin_users_path %>
      <% end %>
<% else %>
    <%= link_to "Sign up", new_user_path %> or
    <%= link_to "Sign In", sign_in_path %>
<% end %>
</p>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>